language: java

sudo: false

matrix:
  include:
    - os: linux
      dist: precise
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: oraclejdk8

# enable Java 8u45+, see https://github.com/travis-ci/travis-ci/issues/4042
addons:
  apt:
    packages:
      - oracle-java8-installer
