language: java

sudo: false

matrix:
  include:
    - os: linux
      dist: precise
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: oraclejdk8

     # Headless Build: `sudo xvfb` + TestFX does not work on Travis OSX environments (as of 2017-05-24)
     # See https://github.com/TestFX/TestFX/issues/396 for more info
    - os: osx
      osx_image: xcode8.2
      env: _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

# enable Java 8u45+, see https://github.com/travis-ci/travis-ci/issues/4042
addons:
  apt:
    packages:
      - oracle-java8-installer
